name: Jobsity Zero Bank Tests
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v4
        timeout-minutes: 10

      - name: Allure report
      # You may pin to the exact commit or the version.
      # uses: afiore/action-allure-report@e43ebd6f4f4c74b07b1eb02f042902bbe6786a19
        uses: afiore/action-allure-report@v0.1.0
        with:
          # Allure test result data dir
          results-dir: allure-results
          # Allure report target dir
          report-dir: allure-report
